# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-12 09:10
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('affiliation', models.CharField(max_length=64)),
                ('floors_above', models.IntegerField(default=1)),
                ('floors_below', models.IntegerField(default=0)),
                ('construction_date', models.DateTimeField(auto_now_add=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('general_info', models.CharField(default='None', max_length=512)),
                ('address', models.CharField(default='None', max_length=256)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('cannot_find_address', models.BooleanField(default=False)),
                ('structure_type', models.CharField(choices=[('Wood', 'Wood'), ('Concrete', 'Concrete'), ('Reinforced Concrete', 'Reinforced Concrete'), ('Reinforced Steel', 'Reinforced Steel'), ('Steel Reinforced Concrete', 'Steel Reinforced Concrete'), ('Steel', 'Steel'), ('Base Isolated', 'Base Isolated'), ('Other', 'Other'), ('Unspecified', 'Unspecified')], default='Unspecified', max_length=20)),
                ('height', models.FloatField(default=0)),
                ('width_ns', models.FloatField(default=0)),
                ('width_ew', models.FloatField(default=0)),
                ('contex_info', models.CharField(default='None', max_length=512)),
                ('acc_top_floor', models.IntegerField(default=-1)),
                ('acc_top_detail', models.CharField(default='None', max_length=512)),
                ('acc_bot_floor', models.IntegerField(default=-1)),
                ('acc_bot_detail', models.CharField(default='None', max_length=512)),
                ('sampling_rate', models.FloatField(default=0)),
                ('conversion_factor', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(default=0)),
                ('intensity', models.FloatField(default=-1)),
                ('acceleration', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('error', models.BooleanField(default=False)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_modification', models.DateTimeField(auto_now_add=True)),
                ('end_modification', models.DateTimeField(auto_now_add=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('occurance', models.CharField(choices=[('Construction', 'Construction'), ('Renovation', 'Renovation'), ('Damage', 'Damage'), ('Other', 'Other')], default='Other', max_length=20)),
                ('comment', models.CharField(max_length=1024)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Building')),
            ],
        ),
    ]
