# Generated by Django 2.0.5 on 2018-05-13 11:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='acceleration',
        ),
        migrations.AddField(
            model_name='event',
            name='acceleration_bot',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[], size=None),
        ),
        migrations.AddField(
            model_name='event',
            name='acceleration_top',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[], size=None),
        ),
        migrations.AddField(
            model_name='event',
            name='predominant_frequency',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='event',
            name='transfer_function',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[], size=None),
        ),
    ]
