# Generated by Django 2.0.5 on 2018-05-14 14:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20180513_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fourier_bot',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[], size=None),
        ),
        migrations.AddField(
            model_name='event',
            name='fourier_top',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[], size=None),
        ),
        migrations.AddField(
            model_name='event',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='construction_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
