# Generated by Django 2.0.5 on 2018-05-19 12:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20180514_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='acc_bot_detail',
            field=models.CharField(blank=True, default='None', max_length=512),
        ),
        migrations.AlterField(
            model_name='building',
            name='acc_top_detail',
            field=models.CharField(blank=True, default='None', max_length=512),
        ),
        migrations.AlterField(
            model_name='building',
            name='affiliation',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='building',
            name='contex_info',
            field=models.CharField(blank=True, default='None', max_length=512),
        ),
        migrations.AlterField(
            model_name='building',
            name='conversion_factor',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='height',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='latitude',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='longitude',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='sampling_rate',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='width_ew',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='width_ns',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='fourier_bot',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='fourier_top',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='intensity',
            field=models.FloatField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='event',
            name='number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='predominant_frequency',
            field=models.FloatField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='event',
            name='transfer_function',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=[], size=None),
        ),
    ]
