# Generated by Django 2.0.5 on 2018-05-19 18:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20180519_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='predominant_frequency',
            new_name='predominant_period',
        ),
        migrations.AddField(
            model_name='building',
            name='graph_predominant_period',
            field=models.ImageField(blank=True, null=True, upload_to='buildings/predominant'),
        ),
        migrations.AddField(
            model_name='building',
            name='graph_predominant_period_smooth',
            field=models.ImageField(blank=True, null=True, upload_to='buildings/smooth/predominant'),
        ),
        migrations.AddField(
            model_name='building',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='buildings/image'),
        ),
        migrations.AddField(
            model_name='building',
            name='predominant_periods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=[], null=True, size=None),
        ),
        migrations.AddField(
            model_name='building',
            name='predominant_periods_smooth',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=[], null=True, size=None),
        ),
        migrations.AddField(
            model_name='event',
            name='acceleration_bot_file',
            field=models.FileField(blank=True, null=True, upload_to='event/acceleration/bot/data'),
        ),
        migrations.AddField(
            model_name='event',
            name='acceleration_top_file',
            field=models.FileField(blank=True, null=True, upload_to='event/acceleration/top/data'),
        ),
        migrations.AddField(
            model_name='event',
            name='acceleration_top_graph',
            field=models.ImageField(blank=True, null=True, upload_to='event/acceleration/bot/graph'),
        ),
        migrations.AddField(
            model_name='event',
            name='fourier_bot_graph',
            field=models.ImageField(blank=True, null=True, upload_to='event/fourier/bot/graph'),
        ),
        migrations.AddField(
            model_name='event',
            name='fourier_bot_graph_smooth',
            field=models.ImageField(blank=True, null=True, upload_to='event/fourier/bot/smooth/graph'),
        ),
        migrations.AddField(
            model_name='event',
            name='fourier_top_graph',
            field=models.ImageField(blank=True, null=True, upload_to='event/fourier/top/graph'),
        ),
        migrations.AddField(
            model_name='event',
            name='fourier_top_graph_smooth',
            field=models.ImageField(blank=True, null=True, upload_to='event/fourier/top/smooth/graph'),
        ),
        migrations.AddField(
            model_name='event',
            name='transfer_function_graph',
            field=models.ImageField(blank=True, null=True, upload_to='event/transfer/graph'),
        ),
        migrations.AddField(
            model_name='event',
            name='transfer_function_graph_smooth',
            field=models.ImageField(blank=True, null=True, upload_to='event/transfer/smooth/graph'),
        ),
        migrations.AlterField(
            model_name='event',
            name='acceleration_bot',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='acceleration_top',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=[], size=None),
        ),
    ]
