# Generated by Django 2.0.5 on 2018-05-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20180519_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='acceleration_bot_graph',
            field=models.ImageField(blank=True, null=True, upload_to='event/acceleration/bot/graph'),
        ),
        migrations.AlterField(
            model_name='event',
            name='acceleration_top_graph',
            field=models.ImageField(blank=True, null=True, upload_to='event/acceleration/top/graph'),
        ),
    ]
