# Generated by Django 2.0.5 on 2018-05-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20180519_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='report'),
        ),
        migrations.AddField(
            model_name='report',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='report'),
        ),
        migrations.AddField(
            model_name='report',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='report'),
        ),
        migrations.AddField(
            model_name='report',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='report'),
        ),
        migrations.AlterField(
            model_name='event',
            name='predominant_period',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
