# Generated by Django 2.0.5 on 2018-05-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20180520_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='error',
            field=models.BooleanField(default=True),
        ),
    ]
