# Generated by Django 2.0.5 on 2018-05-27 14:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20180522_0211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_time']},
        ),
        migrations.AddField(
            model_name='building',
            name='warning_spots',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=[], null=True, size=None),
        ),
    ]
