# Generated by Django 2.0.5 on 2018-06-03 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20180527_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='building_status',
            field=models.CharField(choices=[('Good', 'Good'), ('Caution', 'Caution'), ('Danger', 'Dangerous'), ('Abnormal', 'Abnormal')], default='Good', max_length=50),
        ),
        migrations.AddField(
            model_name='building',
            name='last_renovation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1950, 1, 16, 0, 0)),
        ),
        migrations.AlterField(
            model_name='building',
            name='structure_type',
            field=models.CharField(choices=[('Wood', 'Wood'), ('Concrete', 'Concrete'), ('Reinforced Concrete', 'Reinforced Concrete'), ('Reinforced Steel', 'Reinforced Steel'), ('Steel Reinforced Concrete', 'Steel Reinforced Concrete'), ('Steel', 'Steel'), ('Base Isolated', 'Base Isolated'), ('Other', 'Other'), ('Unspecified', 'Unspecified')], default='Unspecified', max_length=50),
        ),
    ]
