# Generated by Django 2.0.5 on 2018-06-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20180603_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='warning_message',
            field=models.CharField(blank=True, default='None', max_length=512),
        ),
        migrations.AddField(
            model_name='event',
            name='confirmed_not_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='might_be_error',
            field=models.BooleanField(default=False),
        ),
    ]
