# Generated by Django 2.0.5 on 2018-06-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20180603_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='warning_event_num',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
