# Generated by Django 2.0.5 on 2018-06-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_building_warning_event_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='warning_event_num',
            new_name='modified_event',
        ),
        migrations.AlterField(
            model_name='building',
            name='building_status',
            field=models.CharField(choices=[('Good', 'Good'), ('Caution', 'Caution'), ('Danger', 'Dangerous'), ('Abnormal', 'Abnormal'), ('Not Enough Info', 'Not Enough Info')], default='Not Enough Info', max_length=50),
        ),
        migrations.AlterField(
            model_name='building',
            name='warning_message',
            field=models.CharField(blank=True, default='Not Enough Data', max_length=512),
        ),
    ]
