# Generated by Django 2.0.5 on 2018-06-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_auto_20180609_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='begin_modification',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='end_modification',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
