# Generated by Django 2.0.5 on 2018-06-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_auto_20180609_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='begin_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='end_modification',
            field=models.DateTimeField(null=True),
        ),
    ]
